/// Flutter icons ChatIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChatIcon
///      fonts:
///       - asset: fonts/ChatIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChatIcon {
  ChatIcon._();

  static const _kFontFam = 'ChatIcon';
  static const _kFontPkg = null;

  static const IconData icon_chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
